#cache:
#  directories:
#    - node_modules
#    - ~/.cache
#  yarn: true
language: node_js
node_js:
  - "8"
before_script:
  - git submodule update --init --recursive
  - echo "YARN install"
  - yarn install
  - echo "YARN start"
  - yarn start &
script:
  - echo "TEST"
  - yarn test
  - echo "LINT"
  - yarn eslint
  - echo "Build mainnet"
  - yarn build:mainnet
