cache:
  directories:
    - node_modules
  yarn: true
language: node_js
node_js:
  - "8"
matrix:
  iclude:
  - name: "Test"
    env: STAGE=test
  - name: "Lint"
    env: STAGE=lint
  - name: "Build"
    env: STAGE=build:mainnet
before_script:
  - git submodule update --init --recursive
  - if [[ "$STAGE" == "test" ]]; yarn start &; fi
script:
  - if [[ "$STAGE" == "test" ]]; $(npm bin)/cypress run --record; fi
  - if [[ "$STAGE" == "lint" ]]; yarn eslint; fi
  - if [[ "$STAGE" == "build:mainnet" ]]; yarn $STAGE &; fi
