cache: yarn
language: node_js
node_js:
  - "8"
script:
  - git submodule update --init --recursive
  - npm install app-module-path --save
  - ls
  - yarn install
  #- npm test
  - yarn eslint
  - yarn start
