cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  yarn: true
language: node_js
node_js:
  - "8"
matrix:
  iclude:
  - name: "Test"
    env: STAGE=test
  - name: "Lint"
    env: STAGE=lint
  - name: "Build"
    env: STAGE=build:mainnet
  before_script:
    - git submodule update --init --recursive
    - yarn install
    - if [[ "$STAGE" == "test" ]]; then yarn start &; fi
  script:
    - if [[ "$STAGE" == "test" ]]; then $(npm bin)/cypress run --record; fi
    - if [[ "$STAGE" == "lint" ]]; then yarn eslint; fi
    - if [[ "$STAGE" == "build:mainnet" ]];then  yarn $STAGE &; fi
