cache:
  directories:
    - node_modules
    - ~/.cache
  yarn: true
language: node_js
node_js:
  - "8"
before_script:
  - git submodule update --init --recursive
  - echo "_________YARN install___________"
  - yarn install
  - echo "__________YARN start____________"
  - yarn start &
script:
  - echo "____________TEST________________"
  - yarn test
  - echo "____________LINT________________"
  - yarn eslint
  - echo "________Build mainnet___________"
  - yarn build:mainnet
  - echo "________Build testnet___________"
  - yarn build:testnet
  - echo "_________Build local____________"
  - yarn build:local
  - ls
