cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  yarn: true
language: node_js
node_js:
  - "8"
env:
  matrix:
  - STAGE=test
  - STAGE=lint
  - STAGE=build_mainnet
  before_script:
    - git submodule update --init --recursive
    - yarn install
    - if [[ $STAGE == "test" ]]; then yarn start &; fi
  script:
    - if [[ $STAGE == "test" ]]; then cypress install&&$(npm bin)/cypress run --record; fi
    - if [[ $STAGE == "lint" ]]; then yarn eslint; fi
    - if [[ $STAGE == "build_mainnet" ]];then  yarn build:mainnet &; fi
