version: '3'
services:
  mcw_bot:
    build: .
    container_name: mcw_bot
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/root/MulticurrencyWallet/config
      - ${PWD}/.env:/root/MulticurrencyWallet/.env
      - ${PWD}/.storage:/root/MulticurrencyWallet/.storage
