name: Bot tocker build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image src/bot
      run: docker build src/bot --file Dockerfile --tag SObot:$(date +%s)
