name: Build/release

on: push

jobs:
 npm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install `electron-builder` with NPM
        run: |
          npm i
          npm i -D electron-builder@^22.0.0
      - name: Run action
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          app_root: ./test/electron-quick-start/
          package_root: ./test/electron-quick-start/
