name: Build extention

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: npm install, build
      run: |
        npm i
        git config --global user.email "bot@swaponline.io"
        git config --global user.name "buildbot"
    - name: chrome extention
      uses: trmcnvn/chrome-addon@v2
      with:
      # extension is only necessary when updating an existing addon,
      # omitting it will create a new addon
      extension: abcdefg
      zip: build/my-addon.zip
      client-id: ${{ secrets.CHROME_CLIENT_ID }}
      client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      
      env:
        CI: true
        super_secret: ${{ secrets.buildbot }}
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
      
